server:
  port: 11111
  servlet:
    context-path: /

spring:
  redis:
    host: 39.107.221.170
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: abc123
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: abc123
    url: jdbc:mysql://39.107.221.170:3306/tour?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      #空闲连接超时时长
      idle-timeout: 60000
      #连接超时时长
      connection-timeout: 60000
      #最大生命周期, 0不过期
      max-lifetime: 0
      #最小空闲连接数
      minimum-idle: 10
      #最大连接数量
      maximum-pool-size: 10
#  mvc:
#    servlet:
#      这个path就是在最前面加上的前缀，可以在安全配置中使用
#      path: xxxx

mybatis-plus:
  mapper-locations: classpath*:com/chuang/bootplus/mapper/xml/*Mapper.xml
  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
    #mapper-locations: classpath*:mappings/*Mapper.xml




  # 配置日志及命名转换
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true




logging:
  level:
    root: info




jwt:
  header: authorization
  expire: 604800 #7天，秒单位
  secret: ji8n3439n439n43ld9ne9343fdfer49h
